feat(host): More hint routes
ethereum-optimism/kona pull request #232
Opened 2024-06-11 01:30 UTC by clabby

## Overview

Implements several more hint routes in the host program

2024-06-11 01:30 UTC, clabby commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/232?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#232** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/232?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#228** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/228?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#225** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/225?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#210** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/210?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#206** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/206?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#205** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/205?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @clabby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-11 16:25 UTC, refcell commented on bin/host/src/fetcher/mod.rs
> +                // with a more robust solution in the future.
Can we make this and the `L2Code` hint type's `debug_dbGet` use above into tickets to track better?

Strong preference for issues over inline TODO comments for visibility.

2024-06-11 16:26 UTC, refcell requested changes
Small request for github issues over inline TODO comments.

2024-06-14 19:03 UTC, refcell approved these changes

2024-06-14 19:06 UTC, merged