feat(kd8n): derivation test runner for kona-derive
ethereum-optimism/kona pull request #414
Opened 2024-08-02 19:18 UTC by refcell

2024-08-02 19:19 UTC, refcell commented
* **#414** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/414?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @refcell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-21 15:37 UTC, clabby requested changes
This looks like a great start. Let's get it in and iterate.

2024-08-21 15:37 UTC, clabby commented on .gitmodules
> +[submodule "bin/kd8n/op-test-vectors"]
This submodule looks off; Wrong directory.

2024-08-21 18:44 UTC, clabby approved these changes

2024-08-21 18:58 UTC, merged